echo "Ce serveur à été initialisé automatiquement par le script de création de VM. Il est possible que certaines configurations soient à revoir (ex: interface réseau, plage DHCP, etc.)." >&2
echo ""
echo "Jusqu'ici vous avez juste installé une VM, mais il reste à configurer le serveur/client/firewall pour que tout fonctionne."
echo "Le script d'installation se trouve dans le dossier home de l'utilisateur administrateur (ex: /home/administrateur/server-dhcp.sh)."
echo "Si ce fichier est manquant, vous pouvez toujours cloner le dépôt GitHub du projet et récupérer le script dans le dossier guest."
echo "N'oubliez pas de rendre le script exécutable (chmod +x /home/administrateur/server-dhcp.sh) et de l'exécuter en root (sudo /home/administrateur/server-dhcp.sh) pour installer et configurer le serveur DHCP."
echo ""
echo "Dépôt GitHub : https://github.com/kylianjoff/projet-reseaux"
echo "Documentation : https://kylianjoff.github.io/projet-reseaux/"
echo ""
echo "Si vous constatez des problèmes, veuillez dans un premier temps lire la documentation. Sinon contactez moi."
echo ""
echo "Développé par Kylian JULIA"
echo ""